apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service
  namespace: microapp
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP