apiVersion: v1
kind: Service
metadata:
  labels:
    app: front-end-react
  name: front-end-react
  namespace: microapp
spec:
  selector:
    app: front-end-react
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort