apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-service
  name: user-service
  namespace: microapp
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP