apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-service
  name: mongo-service
  namespace: microapp
spec:
  selector:
    app: mongo-service
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP